Example06.WebApplication/Models/ErrorViewModel.cs
namespace Example06.WebApplication.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Example06.WebApplication/Models/Hotel.cs
namespace Example06.WebApplication.Models
{
    public class Hotel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Phone { get; set; }
    }
}

Example06.WebApplication/Controllers/HomeController.cs
using Example06.WebApplication.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Example06.WebApplication.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Example06.WebApplication/Controllers/HotelController.cs
using Example06.WebApplication.Data;
using Example06.WebApplication.Data.Entities;
using Example06.WebApplication.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Example06.WebApplication.Controllers
{
    public class HotelController : Controller
    {
        private AppDbContext _appDbContext;
        private ILogger<HotelController> _logger;
        public HotelController(AppDbContext appDbContext, ILogger<HotelController> logger)
        {
             _appDbContext = appDbContext;
            _logger= logger;    
        }

        // GET: HotleController
        public ActionResult Index()
        {
            var oteller = _appDbContext.Otels.ToList();
            _logger.LogInformation("Oteller sayfası listeleniyor toplam otel sayısı : " + oteller.Count);
            _logger.LogError("Oteller sayfası listeleniyor toplam otel sayısı : " + oteller.Count);
            _logger.LogWarning("Oteller sayfası listeleniyor toplam otel sayısı : " + oteller.Count);
            _logger.LogCritical("Oteller sayfası listeleniyor toplam otel sayısı : " + oteller.Count);
            return View(oteller);
        }

        // GET: HotleController/Details/5
        public ActionResult Details(int id)
        {
            Otel model = _appDbContext.Otels.Single(o => o.Id == id);



            Hotel hotel = new Hotel();
            hotel.Id = model.Id;
            hotel.Name = model.Name;
            hotel.Description = model.Description;
            hotel.Phone = model.Phone;

            return View(hotel);
        }

        // GET: HotleController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: HotleController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Otel model)
        {
            try
            {
                _appDbContext.Otels.Add(model);
                _appDbContext.SaveChanges();
                
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: HotleController/Edit/5
        public ActionResult Edit(int id)
        {
            Otel model = _appDbContext.Otels.Single(o => o.Id == id);

            return View(model);
        }

        // POST: HotleController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Otel newModel)
        {
            try
            {
                Otel oldModel = _appDbContext.Otels.Single(o => o.Id == id);
                oldModel.Name = newModel.Name;
                oldModel.Description = newModel.Description;
                oldModel.Phone= newModel.Phone;

                _appDbContext.Otels.Update(oldModel);
                _appDbContext.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: HotleController/Delete/5
        public ActionResult Delete(int id)
        {

            Otel Model = _appDbContext.Otels.Single(o => o.Id == id);
            return View(Model);
        }


        public ActionResult DeleteConfirm2(int id)
        {
            try
            {
                Otel Model = _appDbContext.Otels.Single(o => o.Id == id);
                _appDbContext.Otels.Remove(Model);
                _appDbContext.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }


        // POST: HotleController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirm(int id)
        {
            try
            {
                Otel Model = _appDbContext.Otels.Single(o => o.Id == id);
                _appDbContext.Otels.Remove(Model);
                _appDbContext.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Example06.WebApplication/Views/Hotel/Create.cshtml
@model Otel

<div class="row">

    <div class="col">
        <form asp-controller="Hotel" asp-action="Create">
           <label asp-for="Name">@Html.DisplayNameFor(m=> m.Name)</label> <input asp-for="Name" class="form-control"/> <br />
            <label asp-for="Description">@Html.DisplayNameFor(m => m.Description)</label> <input asp-for="Description" class="form-control" /> <br />
            <label asp-for="Phone">@Html.DisplayNameFor(m => m.Phone)</label> <input asp-for="Phone" class="form-control" /> <br />

            <input type="submit" value="kaydet" class="btn btn-success"/>
        </form>
    </div>

</div>

Example06.WebApplication/Views/Hotel/Delete.cshtml
@model Otel

<div class="row">
    <div class="col">
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">@Model.Name</h5>
                <h6 class="card-subtitle mb-2 text-body-secondary">@Model.Phone</h6>
                <p class="card-text">@Model.Description</p>

                <form asp-controller="Hotel" asp-action="DeleteConfirm">
                    <input type="hidden" name="Id" value="@Model.Id" />
                    <input type="submit" value="Sil" class="btn btn-danger" />
                </form>

            </div>
        </div>
    </div>
</div>

Example06.WebApplication/Views/Hotel/Details.cshtml
@model Hotel

<div class="row">
     <div class="col">
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">@Model.Name</h5>
                <h6 class="card-subtitle mb-2 text-body-secondary">@Model.Phone</h6>
                <p class="card-text">@Model.Description</p>
                <a asp-controller="Hotel" asp-action="Edit" asp-route-id="@Model.Id" class="card-link text-success">Düzenle</a>
                <a asp-controller="Hotel" asp-action="DeleteConfirm2" asp-route-id="@Model.Id" class="card-link text-danger">Sil</a>
            </div>
        </div>
     </div>
</div>

Example06.WebApplication/Views/Hotel/Edit.cshtml
@model Otel

<div class="row">

    <div class="col">
        <form asp-controller="Hotel" asp-action="Edit">
            <label asp-for="Name">@Html.DisplayNameFor(m => m.Name)</label> <input asp-for="Name" class="form-control" /> <br />
            <label asp-for="Description">@Html.DisplayNameFor(m => m.Description)</label> <input asp-for="Description" class="form-control" /> <br />
            <label asp-for="Phone">@Html.DisplayNameFor(m => m.Phone)</label> <input asp-for="Phone" class="form-control" /> <br />

            <input type="submit" value="kaydet" class="btn btn-success" />
        </form>
    </div>

</div>

Example06.WebApplication/Views/Hotel/Index.cshtml
@model List<Otel>


<a asp-controller="Hotel" asp-action="Create" class="btn btn-success">Ekle</a>


<table class="table">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Adı</th>
            <th scope="col">Açıklama</th>
            <th scope="col">Telefon</th>
            <th scope="col">İşlemler</th>
        </tr>
    </thead>
    <tbody>

        @foreach (Otel otel in Model)
        {
            <tr>
                <td scope="row">@otel.Id</td>
                <td>@otel.Name</td>
                <td>@otel.Description</td>
                <td>@otel.Phone</td>
                <td>
                    <a asp-controller="Hotel" asp-action="Details" asp-route-id="@otel.Id" class="btn btn-primary">Detay</a>
                    <a asp-controller="Hotel" asp-action="Edit" asp-route-id="@otel.Id" class="btn btn-warning">Düzenle</a>
                    <a asp-controller="Hotel" asp-action="Delete" asp-route-id="@otel.Id" class="btn btn-danger">Sil</a>
                </td>
            </tr>
        }

            
        

    </tbody>
    <tfoot>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Adı</th>
            <th scope="col">Açıklama</th>
            <th scope="col">Telefon</th>
            <th scope="col">İşlemler</th>
        </tr>
    </tfoot>

</table>