Example05.WebApplication/Models/Student.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Example05.WebApplication.Models
{
    public class Student
    {
        public int Id { get; set; }

        [Display(Name = "Adı")]
        public string Name { get; set; }

        [Display(Name = "Soyadı")]
        public string Surname { get; set; }

        [EmailAddress]
        [Display(Name = "E-Posta Adresi")]
        public string Email { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Doğum Tarihi")]
        public DateOnly BirthDate { get; set; }

        [Display(Name = "Cinsiyet")]
        public Gender Gender { get; set; }

        [Display(Name = "Öğrenci Durumu")]
        public StudentStatus StudentStatus { get; set; }
    }

    public enum Gender
    {
        [Display(Name = "Kadın")]
        Male,
        [Display(Name = "Erkek")]
        Female
    }

    public enum StudentStatus
    {
        [Display(Name = "Pasif")]
        Passive,
        [Display(Name = "Aktif")]
        Active,
        [Display(Name = "Dondurdu")]
        Frezee
    }
}

Example05.WebApplication/Controllers/StudentController.cs
using Example05.WebApplication.Models;
using Example05.WebApplication.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Example05.WebApplication.Controllers
{
    public class StudentController : Controller
    {
        private const string _pageTitle = "Student";

        // GET: StudentController
        public ActionResult Index()
        {
            ViewBag.Title = $"{_pageTitle} Index";

            ViewData["Baslik"] = "Öğrenciler";


            //ViewBag.KayitDeneme = ViewBag.Deneme ?? "ViewBag.Deneme gelemedi...";
            //ViewData["KayitEkBilgi"] = ViewData["EkBilgi"] ?? "ViewData['EkBilgi'] gelemedi...";

            //string tempData = "TempData['KayitDurumu'] henüz gönderilmedi";

            //if(TempData["KayitDurumu"]  != null)
            //{
            //    tempData = TempData["KayitDurumu"].ToString(); 
            //}

            //ViewBag.KayitTempData = tempData;

            //ViewData["Title"] = "Ben değiştim Hayat :)"; // Bu Title keyi ViewBag de ki property değiştirecektir. AMAN DİKKAT!!!

            List<Student> students = StudentService.Students();

            if (TempData.Any())
            {
                if (TempData["CreateStatus"] != null)
                {
                    if ((bool)TempData["CreateStatus"])
                    {
                        ViewBag.CreateStatus = true;
                    }
                    else
                    {
                        ViewBag.CreateStatus = false;
                    }
                    
                    ViewBag.CreateMessage = TempData["CreateMessage"];
                }
            }


            return View(students);
        }

        // GET: StudentController/Details/5
        public ActionResult Details(int id)
        {
            ViewBag.Title = $"{_pageTitle} Index";
            return View();
        }

        // GET: StudentController/Create
        public ActionResult Create()
        {
            ViewData["Baslik"] = "Yeni Öğrenci";

            Student student = new Student();

            return View(student);
        }

        // POST: StudentController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public ActionResult Create(IFormCollection collection)
        //public ActionResult Create(string name, string surname, string email, string birthDate, string gender, string studentStatus)
        public ActionResult Create(Student student)
        {
            try
            {
                //ViewBag.Deneme = "view Bag geldin mi?";
                //ViewData["EkBilgi"] = "View Data geldin mi?";

                //TempData["KayitDurumu"] = "Kayıt başarılı oldu.";

                //string name = collection["Name"];
                //string surname = collection["Surname"];
                //string email = collection["Email"];
                //string birthDate = collection["BirthDate"];
                //string gender = collection["Gender"];
                //string status = collection["StudentStatus"];

                string name = student.Name;
                string surname = student.Surname;
                string email = student.Email;
                DateOnly birthDate = student.BirthDate;
                Gender gender = student.Gender;
                StudentStatus status = student.StudentStatus;

                StudentService.AddStudent(student);

                TempData["CreateStatus"] = false;
                TempData["CreateMessage"] = $"{name} {surname} sistemimize başarıyla kayıt oldu.";


                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: StudentController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: StudentController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: StudentController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: StudentController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Example05.WebApplication/Controllers/TeacherController.cs
using Example05.WebApplication.Models;
using Example05.WebApplication.Services;
using Microsoft.AspNetCore.Mvc;

namespace Example05.WebApplication.Controllers
{
    public class TeacherController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        //[HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        //public IActionResult Create(string name, string surname, string email)
        //public IActionResult Create(IFormCollection form)
        //public IActionResult Create([Bind("Name","BirthDate")]TeacherViewModel model)
        public IActionResult Create([Bind("Name","BirthDate")]Teacher model)
        {
            model.BirthDate = new DateOnly(2000, 1, 1);
            model.Name += " Kazım";
            //var request = HttpContext.Request;
            //var queryString = request.QueryString;
            //var query = request.Query;

            //if (request.Method == "POST")
            //{
            //    var form = request.Form;

            //    string name = form["Name"];
            //    string surname = form["Surname"];
            //}

            return View(model);
        }
    }
}

Example05.WebApplication/Views/Student/Create.cshtml
@model Student
@{
    Layout = "_StudentLayout";
    ViewBag.Title += "Student Create Page";
}

<form asp-controller="Student" asp-action="Create">
    <div class="mb-3">
        <label asp-for="Name" class="form-label">@Html.DisplayNameFor(m => m.Name)</label>
        <input asp-for="Name" class="form-control" placeholder="@Html.DisplayNameFor(m => m.Name)">

        @*                 <label for="Name" class="form-label">Adınız</label>
        <input name="Name" id="Name" class="form-control" placeholder="Adınız"> *@
    </div>
    <div class="mb-3">
        <label asp-for="Surname" class="form-label">@Html.DisplayNameFor(m => m.Surname)</label>
        <input asp-for="Surname" class="form-control" placeholder="@Html.DisplayNameFor(m => m.Surname)">
    </div>
    <div class="mb-3">
        <label asp-for="Email" class="form-label">@Html.DisplayNameFor(m => m.Email)</label>
        <input asp-for="Email" class="form-control" placeholder="@Html.DisplayNameFor(m => m.Email)">
    </div>
    <div class="mb-3">
        <label asp-for="BirthDate" class="form-label">@Html.DisplayNameFor(m => m.BirthDate)</label>
        <input asp-for="BirthDate" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Gender" class="form-label">@Html.DisplayNameFor(m => m.Gender)</label>
        <select asp-for="Gender" asp-items="Html.GetEnumSelectList<Gender>()" class="form-select"></select>
    </div>
    <div class="mb-3">
        <label asp-for="StudentStatus" class="form-label">@Html.DisplayNameFor(m => m.StudentStatus)</label>
        <select asp-for="StudentStatus" asp-items="Html.GetEnumSelectList<StudentStatus>()" class="form-select"></select>
    </div>
    <div class="mb-3">
        <input type="submit" class="btn btn-primary" value="Kaydet" />
        <input type="reset" class="btn btn-secondary" value="Kaydet" />
    </div>
</form>

Example05.WebApplication/Views/Student/Index.cshtml
@model List<Student>
@{
    Layout = "_StudentLayout";
    ViewBag.Title += "Student Index Page";
}

<div class="d-flex justify-content-end">
    <div class="p-2">
        <a asp-controller="Student" asp-action="Create" class="btn btn-success" role="button">Yeni</a>
    </div>
    <div class="p-2">
        <a asp-controller="Teacher" asp-action="Create" class="btn btn-info" role="button">Yeni Öğretmen</a>
    </div>
    <div class="p-2">
        <a asp-controller="Lesson" asp-action="Create" class="btn btn-warning" role="button">Yeni Ders</a>
    </div>
</div>
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Adı</th>
            <th scope="col">Soyadı</th>
            <th scope="col">Cinsiyeti</th>
            <th scope="col">E-Posta</th>
            <th scope="col">Doğum Tarihi</th>
            <th scope="col">Durumu</th>
            <th scope="col">İşlemler</th>
        </tr>
    </thead>
    <tbody>

        @foreach (Student student in Model)
        {
            <tr>
                <th scope="row">@student.Id</th>
                <td>@student.Name</td>
                <td>@student.Surname</td>
                <td>@student.Gender</td>
                <td>@student.Email</td>
                <td>@student.BirthDate.ToString("dd/MM/yyyy")</td>
                <td>@student.StudentStatus</td>
                <td>
                    @* /Student/Details/1 *@
                    <a asp-controller="Student" asp-action="Details" asp-route-id="@student.Id" class="btn btn-secondary" role="button">Detay</a>
                    <a asp-controller="Student" asp-action="Edit" asp-route-id="@student.Id" class="btn btn-primary" role="button">Düzenle</a>
                    <a asp-controller="Student" asp-action="Delete" asp-route-id="@student.Id" class="btn btn-danger" role="button">Sil</a>

                </td>
            </tr>
        }
    </tbody>
</table>

Example05.WebApplication/Views/Student/_StudentLayout.cshtml
@{
    Layout = "_AnaYapi";
}
<h1 class="m-3">@ViewData["Baslik"].ToString().ToUpper()</h1>

<div class="row mt-5">
    <div class="col-3">
        Bu yazı _StudentLayotu da ekelendi
    </div>
    <div class="col-9">
        @RenderBody()
    </div>
</div>